import type {
  ArtFilter,
  BorderFinish,
  CardKind,
  CardStyle,
  FrameStyle,
  HolofoilPattern,
  MagicType,
  Rarity,
} from '../types/index.js';

export type CatalogSnapshotCard = {
  collectorNumber: number;
  name: string;
  subtitle: string | null;
  description: string | null;
  flavorText: string | null;
  style: CardStyle;
  magicType: MagicType;
  kind: CardKind;
  subtype: string | null;
  rarity: Rarity;
  foil: boolean;
  animated: boolean;
  borderColor: string;
  backColor: string;
  glowColor: string;
  textColor: string;
  frameStyle: FrameStyle;
  holofoilPattern: HolofoilPattern;
  power: number | null;
  toughness: number | null;
  artist: string | null;
  artSeed: string;
  artUrl: string | null;
  stillFile: string | null;
  artFilter: ArtFilter;
  borderFinish: BorderFinish;
  artAnimatedUrl: string | null;
  giphyUrl: string | null;
  animatedUnlockCopies: number;
};

export type CatalogSnapshot = {
  flag: string;
  universe: {
    slug: string;
    name: string;
    tagline: string | null;
    description: string | null;
    accentColor: string;
    backdropColor: string;
  };
  edition: {
    name: string;
    code: string;
    number: number;
    description: string | null;
    releasedAt: string | null;
    coverColor: string;
  };
  cards: CatalogSnapshotCard[];
};

export const CURRENT_CATALOG_SNAPSHOT: CatalogSnapshot = {
  "flag": "current_catalog_snapshot_v1",
  "universe": {
    "slug": "shrek",
    "name": "Shrek",
    "tagline": "Le Swamp",
    "description": null,
    "accentColor": "#26a269",
    "backdropColor": "#0b0614"
  },
  "edition": {
    "name": "Cursed",
    "code": "CURS",
    "number": 1,
    "description": "Les gifs les plus chauds de ta région",
    "releasedAt": null,
    "coverColor": "#8ff0a4"
  },
  "cards": [
    {
      "collectorNumber": 1,
      "name": "Shrek Intensifié",
      "subtitle": "Force incommensurable",
      "description": "Quand Shrek ressent ses émotions. Ses cris boostent ses attaques et terrifient ses ennemis.",
      "flavorText": "L'intensité est la clé de la puissance.",
      "style": "holographic",
      "magicType": "chaos",
      "kind": "creature",
      "subtype": "ogre",
      "rarity": "mythic",
      "foil": false,
      "animated": false,
      "borderColor": "#fb7185",
      "backColor": "#101018",
      "glowColor": "#fb7185",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 6,
      "toughness": 7,
      "artist": "Artiste Anonyme",
      "artSeed": "shrek-intensifie",
      "artUrl": "https://media.giphy.com/media/qIFJYOOi09bk4/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "metallic",
      "artAnimatedUrl": "https://i.giphy.com/qIFJYOOi09bk4.gif",
      "giphyUrl": "https://i.giphy.com/qIFJYOOi09bk4.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 2,
      "name": "Sourire Sinistre",
      "subtitle": "Éclat de malice",
      "description": "Un sourire malicieux qui annonce des plans astucieux. Le Sourire Sinistre booste le moral des alliés.",
      "flavorText": "L'obscurité a souvent un sourire enchanteur.",
      "style": "pixel",
      "magicType": "chaos",
      "kind": "spell",
      "subtype": null,
      "rarity": "mythic",
      "foil": false,
      "animated": false,
      "borderColor": "#fb7185",
      "backColor": "#111827",
      "glowColor": "#fb7185",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Anonyme",
      "artSeed": "sourire-sinistre",
      "artUrl": "https://media.giphy.com/media/QZFs4fM3KZB47e9GZt/giphy_s.gif",
      "stillFile": null,
      "artFilter": "blur",
      "borderFinish": "shiny",
      "artAnimatedUrl": "https://i.giphy.com/QZFs4fM3KZB47e9GZt.gif",
      "giphyUrl": "https://i.giphy.com/QZFs4fM3KZB47e9GZt.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 3,
      "name": "Sourire Sinistre",
      "subtitle": "Un sourire qui raconte des histoires sombres.",
      "description": "Récupérez 5 points de vie et piochez deux cartes.",
      "flavorText": "« Je ne suis pas un ogre ordinaire... »",
      "style": "holographic",
      "magicType": "shadow",
      "kind": "enchantment",
      "subtype": "dark",
      "rarity": "mythic",
      "foil": false,
      "animated": false,
      "borderColor": "#fb7185",
      "backColor": "#101018",
      "glowColor": "#fb7185",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "sourire-sinistre",
      "artUrl": "https://media.giphy.com/media/TIGP3k4gNAqvza2KJK/giphy_s.gif",
      "stillFile": null,
      "artFilter": "chrome",
      "borderFinish": "shiny",
      "artAnimatedUrl": "https://i.giphy.com/TIGP3k4gNAqvza2KJK.gif",
      "giphyUrl": "https://i.giphy.com/TIGP3k4gNAqvza2KJK.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 4,
      "name": "Bépizman Shrek",
      "subtitle": "L'ogre décalé",
      "description": "Une incarnation d'un ogre moderne qui fait sourire. Bépizman Shrek peut échanger des cartes avec d'autres créatures.",
      "flavorText": "Chaque ogre a son propre style.",
      "style": "comic",
      "magicType": "none",
      "kind": "creature",
      "subtype": "ogre",
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#1e1b4b",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 4,
      "toughness": 4,
      "artist": "Artiste Anonyme",
      "artSeed": "bepizman-shrek",
      "artUrl": "https://media.giphy.com/media/YLajJyJBw5ktwRphjf/giphy_s.gif",
      "stillFile": null,
      "artFilter": "neon",
      "borderFinish": "metallic",
      "artAnimatedUrl": "https://i.giphy.com/YLajJyJBw5ktwRphjf.gif",
      "giphyUrl": "https://i.giphy.com/YLajJyJBw5ktwRphjf.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 5,
      "name": "Danse Délirante",
      "subtitle": "Folie rythmique",
      "description": "Une danse qui fait vibrer même les cœurs les plus durs. Cette carte permet de contrôler le rythme du combat.",
      "flavorText": "La danse est la langue secrète de l'âme.",
      "style": "holographic",
      "magicType": "nature",
      "kind": "enchantment",
      "subtype": null,
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#101018",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Anonyme",
      "artSeed": "danse-delirante",
      "artUrl": "/uploads/cards/1790066284364-l28xhq.png",
      "stillFile": "1790066284364-l28xhq.png",
      "artFilter": "holo",
      "borderFinish": "prism",
      "artAnimatedUrl": "https://i.giphy.com/V7jkATiqn3mRie2LI2.gif",
      "giphyUrl": "https://i.giphy.com/V7jkATiqn3mRie2LI2.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 6,
      "name": "Excusez-moi Oui",
      "subtitle": "Interruption impolie",
      "description": "Une carte qui permet de créer le chaos dans une stratégie. Elle interrompt les actions adverses.",
      "flavorText": "La politesse n'a pas sa place dans la guerre.",
      "style": "comic",
      "magicType": "none",
      "kind": "spell",
      "subtype": null,
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#1e1b4b",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Anonyme",
      "artSeed": "excusez-moi-oui",
      "artUrl": "https://media.giphy.com/media/2pMzkCpfejvqhmeRJ2/giphy_s.gif",
      "stillFile": null,
      "artFilter": "holo",
      "borderFinish": "shiny",
      "artAnimatedUrl": "https://i.giphy.com/2pMzkCpfejvqhmeRJ2.gif",
      "giphyUrl": "https://i.giphy.com/2pMzkCpfejvqhmeRJ2.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 7,
      "name": "Grin Étrange",
      "subtitle": "Sourire diabolique",
      "description": "Un sourire qui pourrait faire trembler même les plus courageux. Le Grin Étrange attire les regards et les malédictions.",
      "flavorText": "Un sourire peut cacher bien des secrets.",
      "style": "comic",
      "magicType": "none",
      "kind": "creature",
      "subtype": "ogre",
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#1e1b4b",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 2,
      "toughness": 3,
      "artist": "Artiste Anonyme",
      "artSeed": "grin-etrange",
      "artUrl": "/uploads/cards/1790066256614-xy2fsb.png",
      "stillFile": "1790066256614-xy2fsb.png",
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/LR5GeZFCwDRcpG20PR.gif",
      "giphyUrl": "https://i.giphy.com/LR5GeZFCwDRcpG20PR.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 8,
      "name": "Ogre de Marais",
      "subtitle": "L'ogre paisible",
      "description": "Un simple ogre qui a envie de paix. Son aura calme les âmes tourmentées.",
      "flavorText": "La paix est un trésor inestimable.",
      "style": "watercolor",
      "magicType": "swamp",
      "kind": "creature",
      "subtype": "ogre",
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#1b1530",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 5,
      "toughness": 5,
      "artist": "Artiste Anonyme",
      "artSeed": "ogre-de-marais",
      "artUrl": "https://media.giphy.com/media/1MWtq6NyTgwve/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "prism",
      "artAnimatedUrl": "https://i.giphy.com/1MWtq6NyTgwve.gif",
      "giphyUrl": "https://i.giphy.com/1MWtq6NyTgwve.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 9,
      "name": "Regard Inquiétant",
      "subtitle": "Zoom sur l'angoisse",
      "description": "Un regard qui porte la promesse de mystères non résolus. Le Regard Inquiétant déstabilise les adversaires.",
      "flavorText": "Les yeux sont les fenêtres de l'âme.",
      "style": "watercolor",
      "magicType": "shadow",
      "kind": "spell",
      "subtype": null,
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#1b1530",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Anonyme",
      "artSeed": "regard-inquietant",
      "artUrl": "https://media.giphy.com/media/s2v9H8NgJ10u32CpY3/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/s2v9H8NgJ10u32CpY3.gif",
      "giphyUrl": "https://i.giphy.com/s2v9H8NgJ10u32CpY3.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 10,
      "name": "Regard Radieux",
      "subtitle": "Sourire éclatant",
      "description": "Un sourire qui illumine la pièce. Le Regard Radieux peut guérir et redonner du moral.",
      "flavorText": "La lumière vient d'un sourire.",
      "style": "neon",
      "magicType": "holy",
      "kind": "creature",
      "subtype": "ogre",
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#050816",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 8,
      "toughness": 8,
      "artist": "Artiste Anonyme",
      "artSeed": "regard-radieux",
      "artUrl": "https://media.giphy.com/media/DyxHe19eQxSZ3a7FFr/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "metallic",
      "artAnimatedUrl": "https://i.giphy.com/DyxHe19eQxSZ3a7FFr.gif",
      "giphyUrl": "https://i.giphy.com/DyxHe19eQxSZ3a7FFr.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 11,
      "name": "Sourire du Sommeil",
      "subtitle": "Rêve éveillé",
      "description": "Un sourire qui apaise les cœurs. Ses effets rafraîchissent et restaurent l'énergie.",
      "flavorText": "Le rêve est le gardien de notre sommeil.",
      "style": "stained_glass",
      "magicType": "holy",
      "kind": "spell",
      "subtype": null,
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#14081f",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Anonyme",
      "artSeed": "sourire-du-sommeil",
      "artUrl": "https://media.giphy.com/media/NUfjYIROWpTrma2kHc/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/NUfjYIROWpTrma2kHc.gif",
      "giphyUrl": "https://i.giphy.com/NUfjYIROWpTrma2kHc.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 12,
      "name": "Spongebob Noël",
      "subtitle": "Fête improbable",
      "description": "Quand Noël rencontre l'absurde. Cette carte permet de festivaliser le combat.",
      "flavorText": "Un sourire de Noël peut illuminer les ténèbres.",
      "style": "pixel",
      "magicType": "none",
      "kind": "object",
      "subtype": "decoration",
      "rarity": "legendary",
      "foil": false,
      "animated": false,
      "borderColor": "#fbbf24",
      "backColor": "#111827",
      "glowColor": "#fbbf24",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Anonyme",
      "artSeed": "spongebob-noel",
      "artUrl": "https://media.giphy.com/media/QbvMbYwhBqzvxzYRYI/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "shiny",
      "artAnimatedUrl": "https://i.giphy.com/QbvMbYwhBqzvxzYRYI.gif",
      "giphyUrl": "https://i.giphy.com/QbvMbYwhBqzvxzYRYI.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 13,
      "name": "Rêve Étrange",
      "subtitle": "Un rêve peuplé de créatures bizarres.",
      "description": "Choisissez un personnage, il ne peut pas être ciblé jusqu'à la fin de votre prochain tour.",
      "flavorText": "« Ahhh, parfait... »",
      "style": "stained_glass",
      "magicType": "chaos",
      "kind": "enchantment",
      "subtype": "dream",
      "rarity": "epic",
      "foil": false,
      "animated": false,
      "borderColor": "#c084fc",
      "backColor": "#14081f",
      "glowColor": "#c084fc",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "reve-etrange",
      "artUrl": "https://media.giphy.com/media/bLFQRUZGisPJe/giphy_s.gif",
      "stillFile": null,
      "artFilter": "blur",
      "borderFinish": "prism",
      "artAnimatedUrl": "https://i.giphy.com/bLFQRUZGisPJe.gif",
      "giphyUrl": "https://i.giphy.com/bLFQRUZGisPJe.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 14,
      "name": "Shrek en Fête",
      "subtitle": "Une célébration inattendue.",
      "description": "Récupérez une carte de votre défausse. Si c'est un personnage, il entre sur le champ de bataille avec un bonus de +1/+1.",
      "flavorText": "« Parfois, il faut juste célébrer la vie. »",
      "style": "stained_glass",
      "magicType": "holy",
      "kind": "spell",
      "subtype": "fête",
      "rarity": "epic",
      "foil": false,
      "animated": false,
      "borderColor": "#c084fc",
      "backColor": "#14081f",
      "glowColor": "#c084fc",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "shrek-en-fete",
      "artUrl": "https://media.giphy.com/media/toYIS95xETUPLmU9WP/giphy_s.gif",
      "stillFile": null,
      "artFilter": "holo",
      "borderFinish": "metallic",
      "artAnimatedUrl": "https://i.giphy.com/toYIS95xETUPLmU9WP.gif",
      "giphyUrl": "https://i.giphy.com/toYIS95xETUPLmU9WP.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 15,
      "name": "Baiser Étrange",
      "subtitle": "Un moment d'intimité inattendu.",
      "description": "Choisissez une créature dans votre main. Vous pouvez l'invoquer sans payer son coût. Si c'est une créature ogre, elle gagne +2 en puissance.",
      "flavorText": "« Parfois, l'amour est bizarre. »",
      "style": "holographic",
      "magicType": "holy",
      "kind": "spell",
      "subtype": "enchantment",
      "rarity": "rare",
      "foil": false,
      "animated": false,
      "borderColor": "#60a5fa",
      "backColor": "#101018",
      "glowColor": "#60a5fa",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "baiser-etrange",
      "artUrl": "https://media.giphy.com/media/12bAo3BfU2y6eQ/giphy_s.gif",
      "stillFile": null,
      "artFilter": "neon",
      "borderFinish": "prism",
      "artAnimatedUrl": "https://i.giphy.com/12bAo3BfU2y6eQ.gif",
      "giphyUrl": "https://i.giphy.com/12bAo3BfU2y6eQ.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 16,
      "name": "Danse de l'Ogre",
      "subtitle": "L'ogre qui danse avec passion.",
      "description": "Quand cette carte est jouée, tous les autres personnages gagnent +1 en puissance jusqu'à la fin du tour. Si un personnage est éliminé, vous pouvez piocher une carte.",
      "flavorText": "« Shrek est l'amour, Shrek est la vie ! »",
      "style": "comic",
      "magicType": "chaos",
      "kind": "spell",
      "subtype": "dance",
      "rarity": "rare",
      "foil": false,
      "animated": false,
      "borderColor": "#60a5fa",
      "backColor": "#1e1b4b",
      "glowColor": "#60a5fa",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "danse-de-l-ogre",
      "artUrl": "https://media.giphy.com/media/Te1x8Kmnq63Vm/giphy_s.gif",
      "stillFile": null,
      "artFilter": "holo",
      "borderFinish": "shiny",
      "artAnimatedUrl": "https://i.giphy.com/Te1x8Kmnq63Vm.gif",
      "giphyUrl": "https://i.giphy.com/Te1x8Kmnq63Vm.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 17,
      "name": "Regard de l'Ogre",
      "subtitle": "Un regard qui pétrifie.",
      "description": "Tous les personnages adverses perdent 1 en puissance jusqu'à la fin du tour.",
      "flavorText": "« J'ai un regard perçant ! »",
      "style": "holographic",
      "magicType": "shadow",
      "kind": "spell",
      "subtype": "gaze",
      "rarity": "rare",
      "foil": false,
      "animated": false,
      "borderColor": "#60a5fa",
      "backColor": "#101018",
      "glowColor": "#60a5fa",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "regard-de-l-ogre",
      "artUrl": "/uploads/cards/1790070347708-a6rtuu.png",
      "stillFile": "1790070347708-a6rtuu.png",
      "artFilter": "holo",
      "borderFinish": "neon",
      "artAnimatedUrl": "https://i.giphy.com/xUPGcCh4nUHyCkyuti.gif",
      "giphyUrl": "https://i.giphy.com/xUPGcCh4nUHyCkyuti.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 18,
      "name": "Sourire Malicieux",
      "subtitle": "Un sourire qui cache des intentions obscures.",
      "description": "Inflige 2 points de dégâts à tous les personnages adverses.",
      "flavorText": "« Le sourire du prédateur... »",
      "style": "neon",
      "magicType": "fire",
      "kind": "spell",
      "subtype": "attack",
      "rarity": "rare",
      "foil": false,
      "animated": false,
      "borderColor": "#60a5fa",
      "backColor": "#050816",
      "glowColor": "#60a5fa",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "sourire-malicieux",
      "artUrl": "https://media.giphy.com/media/ggv4eJK7WIScDuWupT/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "metallic",
      "artAnimatedUrl": "https://i.giphy.com/ggv4eJK7WIScDuWupT.gif",
      "giphyUrl": "https://i.giphy.com/ggv4eJK7WIScDuWupT.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 19,
      "name": "Visage de Shrek",
      "subtitle": "Un visage qui fait peur.",
      "description": "L'adversaire doit défausser une carte au hasard. Si c'est un personnage, il perd 2 points de vie.",
      "flavorText": "« Vous ne voulez pas voir mon vrai visage. »",
      "style": "gothic",
      "magicType": "shadow",
      "kind": "spell",
      "subtype": "malédiction",
      "rarity": "rare",
      "foil": false,
      "animated": false,
      "borderColor": "#60a5fa",
      "backColor": "#0f0a12",
      "glowColor": "#60a5fa",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "visage-de-shrek",
      "artUrl": "https://media.giphy.com/media/cy7xq1KHIh2tq/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "swamp",
      "artAnimatedUrl": "https://i.giphy.com/cy7xq1KHIh2tq.gif",
      "giphyUrl": "https://i.giphy.com/cy7xq1KHIh2tq.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 20,
      "name": "Yeux de Chat Potté",
      "subtitle": "Des yeux qui font fondre les cœurs.",
      "description": "Lorsque ce personnage est sur le champ de bataille, tous vos autres personnages gagnent +1 en puissance et en défense.",
      "flavorText": "« Regarde-moi avec ces yeux, et tu feras tout ce que je veux. »",
      "style": "holographic",
      "magicType": "none",
      "kind": "creature",
      "subtype": "chat",
      "rarity": "rare",
      "foil": false,
      "animated": false,
      "borderColor": "#60a5fa",
      "backColor": "#101018",
      "glowColor": "#60a5fa",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 3,
      "toughness": 3,
      "artist": "Artiste Inconnu",
      "artSeed": "yeux-de-chat-potte",
      "artUrl": "https://media.giphy.com/media/qqpiVsIoILNgpBaiaF/giphy_s.gif",
      "stillFile": null,
      "artFilter": "holo",
      "borderFinish": "prism",
      "artAnimatedUrl": "https://i.giphy.com/qqpiVsIoILNgpBaiaF.gif",
      "giphyUrl": "https://i.giphy.com/qqpiVsIoILNgpBaiaF.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 21,
      "name": "Chanson du Marais",
      "subtitle": "Un air mélancolique.",
      "description": "Récupérez 2 points de vie et piochez une carte.",
      "flavorText": "« SONbody once told me... »",
      "style": "watercolor",
      "magicType": "nature",
      "kind": "spell",
      "subtype": "song",
      "rarity": "uncommon",
      "foil": false,
      "animated": false,
      "borderColor": "#34d399",
      "backColor": "#1b1530",
      "glowColor": "#34d399",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "chanson-du-marais",
      "artUrl": "https://media.giphy.com/media/cV7dkMe9oCfSbtfJ4m/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/cV7dkMe9oCfSbtfJ4m.gif",
      "giphyUrl": "https://i.giphy.com/cV7dkMe9oCfSbtfJ4m.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 22,
      "name": "Muffin Man Égaré",
      "subtitle": "Une légende dans le monde des biscuits.",
      "description": "Infligez 3 points de dégâts à un adversaire. Si cet adversaire a une créature, infligez 1 point de dégâts supplémentaire.",
      "flavorText": "« Il est le muffin man ! »",
      "style": "pixel",
      "magicType": "chaos",
      "kind": "object",
      "subtype": "dessert",
      "rarity": "uncommon",
      "foil": false,
      "animated": false,
      "borderColor": "#34d399",
      "backColor": "#111827",
      "glowColor": "#34d399",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "muffin-man-egare",
      "artUrl": "https://media.giphy.com/media/seQilU1T7vDva/giphy_s.gif",
      "stillFile": null,
      "artFilter": "blur",
      "borderFinish": "metallic",
      "artAnimatedUrl": "https://i.giphy.com/seQilU1T7vDva.gif",
      "giphyUrl": "https://i.giphy.com/seQilU1T7vDva.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 23,
      "name": "Ogre Pixelisé",
      "subtitle": "Un regard nostalgique",
      "description": "Cette créature a une défense accrue. Elle peut bloquer une attaque sans perdre de points de vie.",
      "flavorText": "Les souvenirs d'un temps révolu.",
      "style": "pixel",
      "magicType": "nature",
      "kind": "creature",
      "subtype": "ogre",
      "rarity": "uncommon",
      "foil": false,
      "animated": false,
      "borderColor": "#34d399",
      "backColor": "#111827",
      "glowColor": "#34d399",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 3,
      "toughness": 5,
      "artist": "Artiste Inconnu",
      "artSeed": "ogre-pixelise",
      "artUrl": "https://media.giphy.com/media/TzeH3xp9z7ila/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/TzeH3xp9z7ila.gif",
      "giphyUrl": "https://i.giphy.com/TzeH3xp9z7ila.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 24,
      "name": "Prince Charmeur",
      "subtitle": "Le charme à son paroxysme",
      "description": "Lorsque vous jouez cette carte, choisissez un adversaire. Il doit défausser une carte de son choix.",
      "flavorText": "Le charme peut parfois être un piège.",
      "style": "holographic",
      "magicType": "arcane",
      "kind": "spell",
      "subtype": "enchantment",
      "rarity": "uncommon",
      "foil": false,
      "animated": false,
      "borderColor": "#34d399",
      "backColor": "#101018",
      "glowColor": "#34d399",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "prince-charmeur",
      "artUrl": "https://media.giphy.com/media/fJv0eklQfjZX8plZX3/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/fJv0eklQfjZX8plZX3.gif",
      "giphyUrl": "https://i.giphy.com/fJv0eklQfjZX8plZX3.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 25,
      "name": "Réaction du Roi",
      "subtitle": "Un jugement sévère",
      "description": "Inflige 3 dégâts à une créature adverse. Si la créature est de type ogre, inflige 5 dégâts à la place.",
      "flavorText": "La beauté est dans l'œil de celui qui regarde.",
      "style": "neon",
      "magicType": "chaos",
      "kind": "spell",
      "subtype": "action",
      "rarity": "uncommon",
      "foil": false,
      "animated": false,
      "borderColor": "#34d399",
      "backColor": "#050816",
      "glowColor": "#34d399",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "reaction-du-roi",
      "artUrl": "https://media.giphy.com/media/aziUwwr5UAqBy/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/aziUwwr5UAqBy.gif",
      "giphyUrl": "https://i.giphy.com/aziUwwr5UAqBy.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 26,
      "name": "Regard de Shrek",
      "subtitle": "Un regard qui dit tout.",
      "description": "Infligez 2 points de dégâts à une cible. Si cette cible est un personnage, elle ne peut pas attaquer au prochain tour.",
      "flavorText": "« Parfois, un simple regard peut faire plus que des mots. »",
      "style": "gothic",
      "magicType": "shadow",
      "kind": "spell",
      "subtype": "malédiction",
      "rarity": "uncommon",
      "foil": false,
      "animated": false,
      "borderColor": "#34d399",
      "backColor": "#0f0a12",
      "glowColor": "#34d399",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "regard-de-shrek",
      "artUrl": "https://media.giphy.com/media/JaGsFsodf72rtWLlGI/giphy_s.gif",
      "stillFile": null,
      "artFilter": "vignette",
      "borderFinish": "metallic",
      "artAnimatedUrl": "https://i.giphy.com/JaGsFsodf72rtWLlGI.gif",
      "giphyUrl": "https://i.giphy.com/JaGsFsodf72rtWLlGI.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 27,
      "name": "Sourire de l'Ogre",
      "subtitle": "Un sourire qui fait froid dans le dos.",
      "description": "Quand cette carte est jouée, choisissez un personnage adverse. Il ne peut pas attaquer lors de son prochain tour.",
      "flavorText": "« Ça va faire mal ! »",
      "style": "gothic",
      "magicType": "shadow",
      "kind": "spell",
      "subtype": "charm",
      "rarity": "uncommon",
      "foil": false,
      "animated": false,
      "borderColor": "#34d399",
      "backColor": "#0f0a12",
      "glowColor": "#34d399",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "sourire-de-l-ogre",
      "artUrl": "https://media.giphy.com/media/KbgmRs9dUpXQA/giphy_s.gif",
      "stillFile": null,
      "artFilter": "blur",
      "borderFinish": "metallic",
      "artAnimatedUrl": "https://i.giphy.com/KbgmRs9dUpXQA.gif",
      "giphyUrl": "https://i.giphy.com/KbgmRs9dUpXQA.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 28,
      "name": "Baiser de l'Ogre",
      "subtitle": "Un moment inattendu",
      "description": "Lorsque l'Ogre se rapproche, il peut infliger 2 dégâts à un adversaire. Si l'adversaire est un personnage de type créature, il perd 1 point de vie supplémentaire.",
      "flavorText": "L'amour peut être surprenant.",
      "style": "comic",
      "magicType": "chaos",
      "kind": "spell",
      "subtype": "action",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1e1b4b",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "baiser-de-l-ogre",
      "artUrl": "https://media.giphy.com/media/iTYp0KJmalqcU/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/iTYp0KJmalqcU.gif",
      "giphyUrl": "https://i.giphy.com/iTYp0KJmalqcU.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 29,
      "name": "Bébé Ogre Joyeux",
      "subtitle": "Un petit monstre adorable",
      "description": "Cette créature peut attaquer et défendre. Si elle est mise en jeu, vous pouvez piocher une carte supplémentaire.",
      "flavorText": "La joie d'un bébé est contagieuse.",
      "style": "pixel",
      "magicType": "nature",
      "kind": "creature",
      "subtype": "ogre",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#111827",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 2,
      "toughness": 2,
      "artist": "Artiste Inconnu",
      "artSeed": "bebe-ogre-joyeux",
      "artUrl": "https://media.giphy.com/media/RKA9WE5HGkLi8/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/RKA9WE5HGkLi8.gif",
      "giphyUrl": "https://i.giphy.com/RKA9WE5HGkLi8.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 30,
      "name": "Charming Maladroit",
      "subtitle": "Un charme qui tourne mal",
      "description": "Lorsque cette créature entre sur le champ de bataille, elle inflige 2 points de dégâts à un adversaire. Si elle est détruite, l'adversaire doit défausser une carte.",
      "flavorText": "Il ne suffit pas d'avoir l'air beau pour être un bon prince.",
      "style": "comic",
      "magicType": "chaos",
      "kind": "creature",
      "subtype": "humanoid",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1e1b4b",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 3,
      "toughness": 2,
      "artist": "Artiste Inconnu",
      "artSeed": "charming-maladroit",
      "artUrl": "https://media.giphy.com/media/wMqzS9qqe6X2E/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/wMqzS9qqe6X2E.gif",
      "giphyUrl": "https://i.giphy.com/wMqzS9qqe6X2E.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 31,
      "name": "Chat Botté Charmeur",
      "subtitle": "Un sourire irrésistible",
      "description": "Cette créature peut voler. Lorsque Chat Botté Charmeur attaque, vous pouvez piocher une carte. Si vous piochez une carte de la couleur rouge, infligez 3 points de dégâts à un adversaire.",
      "flavorText": "Un regard qui fait fondre les cœurs.",
      "style": "watercolor",
      "magicType": "nature",
      "kind": "creature",
      "subtype": "feline",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1b1530",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 3,
      "toughness": 2,
      "artist": "Inconnu",
      "artSeed": "chat-botte-charmeur",
      "artUrl": "https://media.giphy.com/media/6xNy6UbSKtWpi/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/6xNy6UbSKtWpi.gif",
      "giphyUrl": "https://i.giphy.com/6xNy6UbSKtWpi.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 32,
      "name": "Chœur des Héroïnes",
      "subtitle": "Un appel à l'aide",
      "description": "Tous les personnages alliés gagnent +1 en attaque pour ce tour-ci.",
      "flavorText": "L'union fait la force.",
      "style": "holographic",
      "magicType": "holy",
      "kind": "spell",
      "subtype": "enchantment",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#101018",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "ch-ur-des-heroines",
      "artUrl": "https://media.giphy.com/media/pHbxuhEkyubBR6fkjU/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/pHbxuhEkyubBR6fkjU.gif",
      "giphyUrl": "https://i.giphy.com/pHbxuhEkyubBR6fkjU.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 33,
      "name": "Conversation de Shrek et Âne",
      "subtitle": "Une discussion pleine de surprises.",
      "description": "Permet de piocher deux cartes. Si ce sont des cartes de créature, invoquez-les immédiatement.",
      "flavorText": "« Parfois, parler peut faire toute la différence. »",
      "style": "comic",
      "magicType": "none",
      "kind": "spell",
      "subtype": "discussion",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1e1b4b",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "conversation-de-shrek-et-ane",
      "artUrl": "https://media.giphy.com/media/pKBZfGcYcgzrG/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/pKBZfGcYcgzrG.gif",
      "giphyUrl": "https://i.giphy.com/pKBZfGcYcgzrG.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 34,
      "name": "Danse de l'Ogre",
      "subtitle": "Un pas de danse inattendu",
      "description": "Permet à un personnage de gagner 2 points d'énergie pour une action supplémentaire ce tour-ci.",
      "flavorText": "Quand la musique appelle, même un ogre danse.",
      "style": "watercolor",
      "magicType": "nature",
      "kind": "spell",
      "subtype": "action",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1b1530",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "danse-de-l-ogre",
      "artUrl": "https://media.giphy.com/media/ikiYxuAoXwn9JWtPh2/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/ikiYxuAoXwn9JWtPh2.gif",
      "giphyUrl": "https://i.giphy.com/ikiYxuAoXwn9JWtPh2.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 35,
      "name": "Fiona Éblouissante",
      "subtitle": "Beauté et force réunies",
      "description": "Cette carte permet de récupérer 3 points de vie lorsque vous la jouez. Si elle est ciblée par un sort, annulez-le.",
      "flavorText": "La beauté ne se mesure pas à l'apparence.",
      "style": "watercolor",
      "magicType": "holy",
      "kind": "creature",
      "subtype": "humanoid",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1b1530",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 4,
      "toughness": 5,
      "artist": "Artiste Inconnu",
      "artSeed": "fiona-eblouissante",
      "artUrl": "https://media.giphy.com/media/WQ9wmfmpCt9x37fo1V/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/WQ9wmfmpCt9x37fo1V.gif",
      "giphyUrl": "https://i.giphy.com/WQ9wmfmpCt9x37fo1V.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 36,
      "name": "Foncedé le Shrek",
      "subtitle": "Un sourire qui cache beaucoup.",
      "description": "Quand cette carte est jouée, l'adversaire doit révéler sa main. Vous pouvez choisir une carte de celle-ci et la défausser.",
      "flavorText": "« Quand je souris, c'est que je prépare quelque chose de grand. »",
      "style": "watercolor",
      "magicType": "chaos",
      "kind": "spell",
      "subtype": "illusion",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1b1530",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "sourire-de-shrek",
      "artUrl": "/uploads/cards/1790070399977-cptiyf.png",
      "stillFile": "1790070399977-cptiyf.png",
      "artFilter": "none",
      "borderFinish": "shiny",
      "artAnimatedUrl": "https://i.giphy.com/QPAeF2zTrVheTpyIXv.gif",
      "giphyUrl": "https://i.giphy.com/QPAeF2zTrVheTpyIXv.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 37,
      "name": "Gingembre Écrasé",
      "subtitle": "Le biscuit qui a perdu son éclat.",
      "description": "Inflige 3 points de dégâts à un personnage ciblé. Si ce personnage est un dessert, inflige 5 points de dégâts à la place.",
      "flavorText": "« Tu es un monstre ! »",
      "style": "pixel",
      "magicType": "shadow",
      "kind": "spell",
      "subtype": "curse",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#111827",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "gingembre-ecrase",
      "artUrl": "https://media.giphy.com/media/GtB8bJ7Oypody/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/GtB8bJ7Oypody.gif",
      "giphyUrl": "https://i.giphy.com/GtB8bJ7Oypody.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 38,
      "name": "Ogre en Colère",
      "subtitle": "Un geste malicieux",
      "description": "Lorsque cette carte est jouée, infligez 2 points de dégâts à un adversaire. Si l'adversaire a moins de 10 points de vie, infligez 4 points de dégâts à la place.",
      "flavorText": "Regarde ce que j'en pense !",
      "style": "comic",
      "magicType": "chaos",
      "kind": "spell",
      "subtype": "action",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1e1b4b",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Inconnu",
      "artSeed": "ogre-en-colere",
      "artUrl": "https://media.giphy.com/media/oQO12yv6fSnVUJjvAR/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/oQO12yv6fSnVUJjvAR.gif",
      "giphyUrl": "https://i.giphy.com/oQO12yv6fSnVUJjvAR.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 39,
      "name": "Ombre Terrifiante",
      "subtitle": "La peur dans l'obscurité",
      "description": "Infligez 3 points de dégâts à toutes les créatures ennemies sur le champ de bataille. Cette carte peut être jouée à tout moment.",
      "flavorText": "L'ombre est le reflet de nos peurs.",
      "style": "gothic",
      "magicType": "shadow",
      "kind": "spell",
      "subtype": "spell",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#0f0a12",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "ombre-terrifiante",
      "artUrl": "https://media.giphy.com/media/j603eyZWRPsYjifS7k/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/j603eyZWRPsYjifS7k.gif",
      "giphyUrl": "https://i.giphy.com/j603eyZWRPsYjifS7k.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 40,
      "name": "Pinocchio Maladroit",
      "subtitle": "Un mensonge à la fois",
      "description": "Lorsque Pinocchio est sur le champ de bataille, chaque fois qu'un adversaire joue une carte, il doit défausser une carte.",
      "flavorText": "Les mensonges peuvent mener à des vérités inattendues.",
      "style": "comic",
      "magicType": "chaos",
      "kind": "creature",
      "subtype": "puppet",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1e1b4b",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 1,
      "toughness": 3,
      "artist": "Artiste Inconnu",
      "artSeed": "pinocchio-maladroit",
      "artUrl": "https://media.giphy.com/media/T3nwQFJq5lxFii50fR/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/T3nwQFJq5lxFii50fR.gif",
      "giphyUrl": "https://i.giphy.com/T3nwQFJq5lxFii50fR.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 41,
      "name": "Regard de l'Âne",
      "subtitle": "La curiosité peut mener à des situations étranges.",
      "description": "Lorsque cette carte est jouée, piochez deux cartes. Si une de ces cartes est une créature, vous pouvez l'invoquer immédiatement.",
      "flavorText": "« Est-ce que je peux rester ici ? »",
      "style": "watercolor",
      "magicType": "nature",
      "kind": "spell",
      "subtype": "enchantment",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1b1530",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "regard-de-l-ane",
      "artUrl": "https://media.giphy.com/media/Sr9NHwRKlsD3unMK43/giphy_s.gif",
      "stillFile": null,
      "artFilter": "holo",
      "borderFinish": "shiny",
      "artAnimatedUrl": "https://i.giphy.com/Sr9NHwRKlsD3unMK43.gif",
      "giphyUrl": "https://i.giphy.com/Sr9NHwRKlsD3unMK43.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 42,
      "name": "Regard Étonné",
      "subtitle": "Une réaction inattendue",
      "description": "Cette carte peut annuler une action adverse. L'adversaire perd 1 point de vie.",
      "flavorText": "La surprise est parfois la meilleure défense.",
      "style": "gothic",
      "magicType": "shadow",
      "kind": "spell",
      "subtype": "action",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#0f0a12",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": null,
      "toughness": null,
      "artist": "Artiste Inconnu",
      "artSeed": "regard-etonne",
      "artUrl": "https://media.giphy.com/media/iJxHU0Fo2uMxLlmWgd/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/iJxHU0Fo2uMxLlmWgd.gif",
      "giphyUrl": "https://i.giphy.com/iJxHU0Fo2uMxLlmWgd.gif",
      "animatedUnlockCopies": 5
    },
    {
      "collectorNumber": 43,
      "name": "Sourire de l'Âne",
      "subtitle": "Un sourire qui ne s'oublie jamais.",
      "description": "Lorsque cette créature entre sur le champ de bataille, choisissez un joueur. Ce joueur doit piocher une carte supplémentaire. Si c'est un tour d'ennemi, il perd 1 point de vie.",
      "flavorText": "« Je suis l'Âne, et je suis ici pour faire sourire tout le monde ! »",
      "style": "comic",
      "magicType": "none",
      "kind": "creature",
      "subtype": "âne",
      "rarity": "common",
      "foil": false,
      "animated": false,
      "borderColor": "#94a3b8",
      "backColor": "#1e1b4b",
      "glowColor": "#94a3b8",
      "textColor": "#f4efe6",
      "frameStyle": "classic",
      "holofoilPattern": "none",
      "power": 2,
      "toughness": 2,
      "artist": "Artiste Inconnu",
      "artSeed": "sourire-de-l-ane",
      "artUrl": "https://media.giphy.com/media/KEf7gXqvQ8B3SWnUid/giphy_s.gif",
      "stillFile": null,
      "artFilter": "none",
      "borderFinish": "matte",
      "artAnimatedUrl": "https://i.giphy.com/KEf7gXqvQ8B3SWnUid.gif",
      "giphyUrl": "https://i.giphy.com/KEf7gXqvQ8B3SWnUid.gif",
      "animatedUnlockCopies": 5
    }
  ]
};
